### PR TITLE
Simplify map call.

### PR DESCRIPTION
**Pull request by ben-eb**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yeah, I had it like that initially, but I'm beginning to think it's an anti-pattern. Especially now that we have arrow functions. What if `string-width` suddenly gets support for a second argument. It will then be implicitly passed the index from the `map` callback and everything will break. This could happen in a semver-minor as it's not semantically a breaking change. Thoughts?

**Comment by ben-eb** [comment]
Yeah, that's true; kind of like how you can't map a value through `parseInt`. I think realistically then it makes sense to keep the module as is, because it won't lead to future bugs. It's probably still OK to do the style proposed in client code (where you can control each piece), but probably not for modules. :+1:

**Comment by sindresorhus** [comment]
Yup, that's a good conclusion. With arrow functions it would be almost as nice anyways:

``` js
return Math.max.apply(null, str.split('\n').map(x => stringWidth(x)));
```

**Comment by sindresorhus** [comment]
And with `spread`:

``` js
return Math.max(...str.split('\n').map(x => stringWidth(x)));
```

**Comment by ben-eb** [comment]
Yep, `spread` makes this much more readable. :smile:

**Pull request closed without merging**
